### ISSUE TITLE
Is info/collections still used?

### ISSUE THREAD

**Issue by michielbdejong** [mozilla-services/docs#55]
In https://github.com/mozilla-services/docs/blob/368cc63d1e01583abef022ee5fc9b630c53eb102/source/sync/lifeofasync.rst#fetch-infocollections it says we should retrieve info/collections, but in practice it seems this data has been moved into meta/global . engines? Is that page outdated?

**Comment by michielbdejong** [comment]
See https://docs.services.mozilla.com/sync/storageformat5.html#metaglobal-record

**Comment by ncalexan** [comment]
@michielbdejong both `i/c` and `m/g` are necessary.  They serve different purposes: `i/c` yields information about collections on the server and `m/g` allows clients to co-ordinate what they do as a group.  There's no authoritative documentation on what a "compliant" Sync client does, but the cleanest implementation is in Swift at https://github.com/mozilla/firefox-ios/blob/master/Sync/SyncStateMachine.swift and the accompanying state machine diagram is at http://people.mozilla.org/~nalexander/SyncStateMachine.pdf.  That might help you see how `i/c` is used to determine what's fresh and stale, and `m/g` is used to determine different things.

**Comment by michielbdejong** [comment]
@ncalexan Thanks! I found out that the reason I seeing 404s for `i/c` was that I was effectively trying to fetch `/storage/info/collections` instead of `/info/collections`.

**Comment by ncalexan** [comment]
On Mon, Nov 16, 2015 at 12:43 AM, Michiel de Jong <notifications@github.com>
wrote:

> @ncalexan <https://github.com/ncalexan> Thanks! I found out that the
> reason I seeing 404s for i/c was that I was effectively trying to fetch
> /storage/info/collections instead of /info/collections.
>
Glad you figured it out.  The logic here is that `i/c` is special --
generated by the server, can't `PUT` to it -- so it's not under `/storage`.
